deployment:
  tasks:
    - echo "Starting deployment..."
    - cd /home/abacygmx/repositories/kidseducation
    - git pull origin master
    - export COMPOSER_ALLOW_SUPERUSER=1
    - /opt/cpanel/ea-php82/root/usr/bin/php /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader
    - npm install
    - npm run build
    - echo "Copying public/build to public_html/build..."
    - rm -rf /home/abacygmx/public_html/build
    - cp -r /home/abacygmx/repositories/kidseducation/public/build /home/abacygmx/public_html/build
    - export DEPLOYPATH=/home/abacygmx
    - echo "Deploying from repo to public_html"
    - cp -r public/build $DEPLOYPATH/public_html/
    - cp public/index.php $DEPLOYPATH/public_html/
    - cp public/.htaccess $DEPLOYPATH/public_html/
    - echo "Deployment complete."
