---
deployment:
  tasks:
    - export DEPLOYPATH=/home/abacygmx/public_html/
    - /bin/cp -R repositories/kidseducation/public/* $DEPLOYPATH
    - export APPPATH=/home/abacygmx/repositories/kidseducation/
    - /bin/cp -R $APPPATH/app $DEPLOYPATH/../
    - /bin/cp -R $APPPATH/bootstrap $DEPLOYPATH/../
    - /bin/cp -R $APPPATH/config $DEPLOYPATH/../
    - /bin/cp -R $APPPATH/database $DEPLOYPATH/../
    - /bin/cp -R $APPPATH/resources $DEPLOYPATH/../
    - /bin/cp -R $APPPATH/routes $DEPLOYPATH/../
    - /bin/cp -R $APPPATH/storage $DEPLOYPATH/../
    - /bin/cp $APPPATH/.env $DEPLOYPATH/../
    - /bin/cp $APPPATH/artisan $DEPLOYPATH/../
    - /bin/cp $APPPATH/composer.json $DEPLOYPATH/../
    - /bin/cp $APPPATH/composer.lock $DEPLOYPATH/../
    - cd $DEPLOYPATH/../ && /usr/local/bin/php /opt/cpanel/composer/bin/composer install --no-dev
    - cd $DEPLOYPATH/../ && /usr/local/bin/php artisan migrate --force
    - cd $DEPLOYPATH/../ && /usr/local/bin/php artisan cache:clear
    - cd $DEPLOYPATH/../ && /usr/local/bin/php artisan config:clear
    - cd $DEPLOYPATH/../ && /usr/local/bin/php artisan view:clear
    - cd $DEPLOYPATH/../ && /usr/local/bin/php artisan route:clear
    - cd $DEPLOYPATH/../ && /usr/local/bin/npm install
    - cd $DEPLOYPATH/../ && /usr/local/bin/npm run build
