// resources/js/Utils/iconMapping.jsx
import {
    BookOpen,
    Code,
    Calculator,
    User,
    Calendar,
    Trophy,
    Play,
    FileText,
    Palette,
    Music,
    Puzzle,
    Zap,
    Globe,
    Brain,
    Gamepad2,
    Microscope,
    Brush,
    Camera,
    PenTool,
    Beaker,
    Rocket,
    Heart,
    Star,
    Lightbulb,
    Target,
    Shield,
    Crown,
    Gem,
    Wand2,
    Sparkles,
    School,
    GraduationCap,
    Apple,
    Atom,
    FlaskConical,
    Languages,
    MapPin,
    Mountain,
    Leaf,
    Trees,
    Sun,
    Moon,
    Cloud,
    Flower2,
    Bug,
    Fish,
    Bird,
    Cat,
    Dog,
    Rabbit,
    Smile,
    Gift,
    Dice1,
    Dice2,
    Dice3,
    Dice4,
    Dice5,
    Dice6,
    Shapes,
    Circle,
    Square,
    Triangle,
    Construction,
    Hammer,
    Wrench,
    Scissors,
    Ruler
} from "lucide-react";

export const iconMap = {
    // Core Education
    BookOpen: BookOpen,
    Calculator: Calculator,
    Code: Code,
    GraduationCap: GraduationCap,
    School: School,
    
    // Mathematics & Logic
    "Dice1": Dice1,
    "Dice2": Dice2,
    "Dice3": Dice3,
    "Dice4": Dice4,
    "Dice5": Dice5,
    "Dice6": Dice6,
    Shapes: Shapes,
    Circle: Circle,
    Square: Square,
    Triangle: Triangle,
    Target: Target,
    
    // Creative Arts
    Palette: Palette,
    Brush: Brush,
    PenTool: PenTool,
    Camera: Camera,
    Music: Music,
    
    // Science & Discovery
    Microscope: Microscope,
    Beaker: Beaker,
    FlaskConical: FlaskConical,
    Atom: Atom,
    Rocket: Rocket,
    Brain: Brain,
    Lightbulb: Lightbulb,
    
    // Technology & Games
    Gamepad2: Gamepad2,
    Zap: Zap,
    Wand2: Wand2,
    
    // Nature & World
    Globe: Globe,
    MapPin: MapPin,
    Mountain: Mountain,
    Leaf: Leaf,
    Trees: Trees,
    Sun: Sun,
    Moon: Moon,
    Cloud: Cloud,
    Flower2: Flower2,
    
    // Animals
    Bug: Bug,
    Fish: Fish,
    Bird: Bird,
    Cat: Cat,
    Dog: Dog,
    Rabbit: Rabbit,
    
    // Tools & Construction
    Construction: Construction,
    Hammer: Hammer,
    Wrench: Wrench,
    Scissors: Scissors,
    Ruler: Ruler,
    
    // Languages & Communication
    Languages: Languages,
    Apple: Apple,
    
    // Rewards & Achievement
    Trophy: Trophy,
    Crown: Crown,
    Star: Star,
    Gem: Gem,
    Shield: Shield,
    Heart: Heart,
    
    // Fun & Play
    Puzzle: Puzzle,
    Sparkles: Sparkles,
    Gift: Gift,
    Smile: Smile,
    
    // Media & Content
    Play: Play,
    FileText: FileText,
    User: User,
    Calendar: Calendar,
};
