name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
    types: [ opened, synchronize, reopened, ready_for_review ]

env:
  NODE_VERSION: '18'
  PHP_VERSION: '8.2'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    if: github.event.pull_request.draft == false

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: kids_education_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ env.PHP_VERSION }}
        extensions: mbstring, dom, fileinfo, mysql, bcmath, gd, zip, curl
        coverage: xdebug

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

    - name: Install Composer dependencies
      run: |
        composer install --no-progress --prefer-dist --optimize-autoloader --no-dev
        composer dump-autoload

    - name: Install NPM dependencies
      run: npm ci

    - name: Create testing environment file
      run: |
        # Create SQLite file as fallback to prevent errors during config operations
        mkdir -p database
        touch database/database.sqlite
        chmod 666 database/database.sqlite
        ls -la database/
        echo "SQLite file created at: $(pwd)/database/database.sqlite"
        
        # Create .env.testing
        cp .env.example .env.testing
        sed -i 's/DB_CONNECTION=sqlite/DB_CONNECTION=mysql/' .env.testing
        sed -i 's/CACHE_STORE=database/CACHE_STORE=array/' .env.testing
        sed -i 's/SESSION_DRIVER=database/SESSION_DRIVER=array/' .env.testing
        sed -i 's/QUEUE_CONNECTION=database/QUEUE_CONNECTION=sync/' .env.testing
        echo "APP_ENV=testing" >> .env.testing
        echo "DB_HOST=127.0.0.1" >> .env.testing
        echo "DB_PORT=3306" >> .env.testing
        echo "DB_DATABASE=kids_education_test" >> .env.testing
        echo "DB_USERNAME=root" >> .env.testing
        echo "DB_PASSWORD=password" >> .env.testing
        echo "MAIL_MAILER=array" >> .env.testing
        
        # Create .env (same as testing for CI)
        cp .env.testing .env
        
        # Debug: Show the final configuration
        echo "=== Final .env file ==="
        cat .env | grep -E "(DB_|CACHE_|SESSION_|QUEUE_)"

    - name: Generate application key
      run: |
        php artisan key:generate
        php artisan key:generate --env=testing

    - name: Wait for MySQL to be ready
      run: |
        until nc -z 127.0.0.1 3306; do
          echo "Waiting for MySQL..."
          sleep 1
        done
        echo "MySQL is ready!"

    - name: Clear any existing caches
      run: |
        # Debug: Check current environment
        echo "=== Current working directory ==="
        pwd
        echo "=== Database file status ==="
        ls -la database/ || echo "Database directory not found"
        echo "=== Environment variables ==="
        env | grep -E "(DB_|CACHE_|SESSION_|QUEUE_)" || echo "No DB/Cache env vars found"
        
        # Remove any cached configuration files that might reference SQLite
        rm -f bootstrap/cache/config.php
        rm -f bootstrap/cache/packages.php
        rm -f bootstrap/cache/services.php
        
        # Debug: Check Laravel configuration
        echo "=== Laravel config check ==="
        php artisan env
        
        # Clear application caches
        php artisan config:clear
        php artisan cache:clear
        php artisan view:clear

    - name: Run database migrations
      run: php artisan migrate --env=testing --force

    - name: Seed database
      run: php artisan db:seed --env=testing --force

    - name: Build frontend assets
      run: npm run build

    - name: Run PHP tests
      run: php artisan test --env=testing --coverage-text --colors=never

    - name: Run PHP Static Analysis (PHPStan)
      run: |
        composer require --dev phpstan/phpstan --no-update
        composer update phpstan/phpstan
        ./vendor/bin/phpstan analyse --memory-limit=2G || true

    - name: Run Code Style Check (PHP CS Fixer)
      run: |
        composer require --dev friendsofphp/php-cs-fixer --no-update
        composer update friendsofphp/php-cs-fixer
        ./vendor/bin/php-cs-fixer fix --dry-run --diff || true

  build:
    runs-on: ubuntu-latest
    name: Build Application
    needs: test
    if: github.event.pull_request.draft == false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ env.PHP_VERSION }}
        extensions: mbstring, dom, fileinfo, mysql, bcmath, gd, zip

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

    - name: Install Composer dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader --no-dev

    - name: Install NPM dependencies
      run: npm ci

    - name: Build frontend assets for production
      run: npm run build

    - name: Optimize Laravel for production
      run: |
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: built-app
        path: |
          public/build/
          bootstrap/cache/
        retention-days: 7

  security-scan:
    runs-on: ubuntu-latest
    name: Security Scan
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ env.PHP_VERSION }}

    - name: Install Composer dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - name: Run security audit
      run: |
        composer require --dev enlightn/security-checker --no-update
        composer update enlightn/security-checker
        ./vendor/bin/security-checker security:check composer.lock || true

    - name: Run npm audit
      run: npm audit --audit-level high || true

  code-quality:
    runs-on: ubuntu-latest
    name: Code Quality Checks
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install NPM dependencies
      run: npm ci

    - name: Run ESLint
      run: |
        npm install eslint @eslint/js eslint-plugin-react eslint-plugin-react-hooks --save-dev
        npx eslint resources/js --ext .js,.jsx --max-warnings 0 || true

    - name: Run Prettier check
      run: |
        npm install prettier --save-dev
        npx prettier --check resources/js/**/*.{js,jsx} || true

    - name: Check for large files
      run: |
        find . -type f -size +50M -not -path "./vendor/*" -not -path "./node_modules/*" -not -path "./.git/*" || true